### ISSUE TITLE
[BUG] Exception with scikit-learn >=1.3.0

### ISSUE THREAD

**Issue by DManowitz** [heidelbergcement/hcrystalball#76]
**Describe the bug**
This package raises an exception when trying to import hcrystallball.metrics with scikit-learn >=1.3.0

**To Reproduce**
install hcrystallball into a new (Python >=3.8) environment along with scikit-learn>=1.3.0.
Attempt to import hcrystallball.metrics

Note the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\hcrystalball\metrics\__init__.py", line 1, in <module>
    from ._scorer import get_scorer
  File "C:\...\lib\site-packages\hcrystalball\metrics\_scorer.py", line 5, in <module>
    from sklearn.metrics import SCORERS
ImportError: cannot import name 'SCORERS' from 'sklearn.metrics' (C:\...\lib\site-packages\sklearn\metrics\__init__.py)
```

**Expected behavior**
no exception

**Screenshots**
N/A

**Additional context**
SCORERS has been removed from `sklearn.metrics` as of [1.3.0](https://github.com/scikit-learn/scikit-learn/blob/1.3.0/sklearn/metrics/__init__.py)

**Comment by SmirnGregHM** [comment]
Hello @DManowitz! Thank you for the interest in hcrystalball

1. The project is currently not maintained. Our team shifted to work with another open source package, `sktime`, which is actively maintained.
2. We have encountered this issue, too, and resolved it with https://github.com/heidelbergcement/hcrystalball/pull/75. It did not pass the pipeline though, and we don't have enough resources to investigate it. You can use the wheel under `git+https://github.com/heidelbergcement/hcrystalball.git@python-update`, but we also can't guarantee that the branch will leave forever. 
3. If you have interest in hcrystalball, you are free to fork it and maintain it under MIT license.

I leave the issue open so other people can find this information on top of the issues list.

**Comment by DManowitz** [comment]
@SmirnGregHM, if this project is not currently maintained, I think you should at least add this information to the top of the README so that it is obvious to anyone who looks at this repo.  You might also want to archive the repo.
